cloudCredentialSecretName: cattle-global-data:cc-q45sl #! this value had to be looked up
cloudprovider: harvester
cluster:
  annotations: {}
  labels: 
    environment: dev
    cluster_name: alpha

  #! must be a unique name
  name: rke2-small-demo-alpha 

kubernetesVersion: v1.24.2+rke2r1
monitoring:
  enabled: false
rke:
  localClusterAuthEndpoint:
    enabled: false

nodepools:
#! name field must be unique across all clusters
- name: demo-control-plane-alpha
  displayName: control-plane
  etcd: true
  controlplane: true
  worker: false

  # specify node labels
  labels: {}

  # specify node taints
  taints: {}

  # specify nodepool size
  quantity: 1
  diskSize: 20
  diskBus: virtio
  cpuCount: 2
  memorySize: 4
  networkName: default/workloads
  networkType: dhcp
  imageName: default/image-4jz2k #! this value had to be looked up
  vmNamespace: default
  sshUser: ubuntu

#! name field must be unique across all clusters
- name: demo-worker-alpha
  displayName: worker
  worker: true

  # specify node labels
  labels: {}

  # specify node taints
  taints: {}

  # specify nodepool size
  quantity: 3
  diskSize: 20
  diskBus: virtio
  cpuCount: 2
  memorySize: 4
  networkName: default/workloads
  networkType: dhcp
  imageName: default/image-4jz2k #! this value had to be looked up
  vmNamespace: default
  sshUser: ubuntu

