cloudCredentialSecretName: cattle-global-data:cc-wqgrc #! this value had to be looked up
cloudprovider: harvester
cluster:
  annotations: {}
  labels: 
    environment: shared
    cluster_name: services

  #! must be a unique name
  name: rke2-shared-services

kubernetesVersion: v1.23.7+rke2r2
monitoring:
  enabled: false
rke:
  localClusterAuthEndpoint:
    enabled: false

nodepools:
#! name field must be unique across all clusters
- name: shared-control-plane-services
  displayName: control-plane
  etcd: true
  controlplane: true
  worker: false

  # specify node labels
  labels: {}

  # specify node taints
  taints: {}

  # specify nodepool size
  quantity: 3
  diskSize: 40
  diskBus: virtio
  cpuCount: 4
  memorySize: 8
  networkName: default/workloads
  networkType: dhcp
  imageName: default/image-tc258 #! this value had to be looked up
  vmNamespace: default
  sshUser: ubuntu

#! name field must be unique across all clusters
- name: shared-worker-services
  displayName: worker
  worker: true

  # specify node labels
  labels: {}

  # specify node taints
  taints: {}

  # specify nodepool size
  quantity: 3
  diskSize: 40
  diskBus: virtio
  cpuCount: 4
  memorySize: 8
  networkName: default/workloads
  networkType: dhcp
  imageName: default/image-tc258 #! this value had to be looked up
  vmNamespace: default
  sshUser: ubuntu

