kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: app-platform
  namespace: fleet-default
spec:
  repo: https://github.com/bcdurden/fleet-demo.git
  branch: main

  # To target specific clusters, uncomment this block
  targets:
  - clusterSelector:
      matchLabels:
        environment: dev

  paths:
  - "./gitops/apps/app_platform/"